name: 'Install changelog generator for the Github release'
description: 'Github action that generaters a changelog and create a release in Github.'
author: 'andrejpetras'
branding:
  icon: edit
  color: blue
inputs:
  version:
    description: 'Version of the changelog utility'
    required: false
    default: '1.6.0'
  download_url:
    description: 'Download changelog URL template.'
    required: false
    default: 'https://github.com/lorislab/changelog/releases/download/${version}/changelog_Linux_x86_64.tar.gz'
outputs: {}
runs:
  using: 'node20'
  main: 'dist/index.js'
